<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class SessionTest extends TestCase
{
    protected $cookie = 'abcc123123';

    protected $cookie1 = '';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $response = $this->put(route('api.session.put.1', ['value' => 100]));
        $response->assertContent("100");
        $cookie = $response->getCookie('laravel_session', true);
        $this->cookie1 = $cookie->getValue();
    }

    /**
     * A basic feature test example.
     */
    public function test_example(): void
    {

        $response = $this->get('/');

        $response->assertStatus(200);
    }

    public function test_api_route_session_put()
    {
        $response = $this->put(route('api.session.put.1', ['value' => 1]));
        $response->assertContent("1");
        $cookie = $response->getCookie('laravel_session', false);
        $this->cookie1 = $cookie;
//        $response->assertContent(1);

    }

    public function test_api_route_session_get()
    {
        $response = $this->withCookie('laravel_session', $this->cookie1)->get(route('api.session.get.1', ['value' => 100]));
        $response->assertContent("100");
    }

    public function test_web_route_session_put()
    {
//        $cookie = 'abc123123';
        $response = $this->withCookie('laravel_session', $this->cookie)->get(route('web.session.put.1', ['value' => 1]), [], ['Accept' => 'application/json']);
        $response->assertContent("1");
//        $response->assertContent(1);
        $response = $this->withCookie('laravel_session', $this->cookie)->get(route('web.session.get.1', ['value' => 1]));
        $response->assertContent("1");

    }


    public function test_web_route_session_put1()
    {
//        $cookie = 'abc123123';
        $response = $this->get(route('web.session.put.1', ['value' => 1]), [], ['Accept' => 'application/json']);
        $response->assertContent("1");
//        $response->assertContent(1);
        $response = $this->get(route('web.session.get.1', ['value' => 1]));
        $response->assertContent("1");

    }
    public function test_web_route_session_get()
    {
        $response = $this->withCookie('laravel_session', $this->cookie)->get(route('web.session.get.1', ['value' => 1]));
        $response->assertContent("");
    }
}
