<?php

namespace Tests\Unit;

use utils\Calculator1;
use PHPUnit\Framework\TestCase;

class Calculator1Test extends TestCase
{
    private Calculator1 $calculator1;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->calculator1 = new Calculator1();
    }

    public function testAdd()
    {
        $res = $this->calculator1->add(1, 3.2);
        $this->assertEquals(1 + 3.2, $res);
    }

    public function testSub()
    {
        $res = $this->calculator1->sub(8.2, 7);
        $this->assertEquals(8.2 - 7, $res);
    }
    public function testTimes()
    {
        $res = $this->calculator1->times(8.2, 7);
        $this->assertEquals(8.2 * 7, $res);
    }
    public function testDivide()
    {
        $res = $this->calculator1->divide(8.2, 7);
        $this->assertEquals(8.2 / 7, $res);

        $res = $this->calculator1->divide(0, 7);
        $this->assertEquals(0, $res);

        $res = $this->calculator1->divide(0, 0);
        $this->assertEx(0, $res);

    }

}
